### PR TITLE
Docs: update to reflect logging configuration changes

### PR DESCRIPTION
**Pull request by ikeith**
Documentation companion to https://github.com/ionic-team/capacitor/pull/4416

### CODE REVIEW

**Review by jcesarmobile — CHANGES_REQUESTED** [review]
The config changes should be done on the [v3 config docs](https://github.com/ionic-team/capacitor-site/blob/main/pages/docs/v3/config/index.md), you made them on the v2 ones.

Same for console API, but I've noticed that we don't have a console section on v3 (probably because they are now generated from plugins and Console is not a real plugin)

**Comment by ikeith** [comment]
> The config changes should be done on the [v3 config docs](https://github.com/ionic-team/capacitor-site/blob/main/pages/docs/v3/config/index.md), you made them on the v2 ones.

Whoops, good catch. Since the `Console` docs are gone, I've expanded the inline documentation in the declaration file both here and in the main repo.

**Review by jcesarmobile — APPROVED** [review]
Looks good.

Not sure if we might want to leave the hideLogs as it's still there despite it's deprecated, or if it's better to remove it so people don't use it.
We might want to document in the capacitor 3 upgrade guide that `hideLogs` is deprecated and that they should move to `loggingBehavior`

**Comment by ikeith** [comment]
Updated the upgrade guide.

**Pull request merged**
