### PR TITLE
fix typo on web plugin permission docs 

### PR DESCRIPTION
**Pull request by robingenz**
`PermissionState` should be `PermissionStatus`.

### CODE REVIEW

**Comment by thomasvidas** [comment]
In v3 and v2, the TS definition is [PermissionState](https://github.com/ionic-team/capacitor/blob/0429905efcf69097e7759b8d21d74459b8dd42c5/core/src/definitions.ts#L124), not `PermissionStatus`.

**Comment by robingenz** [comment]
In line 75, the interface uses `PermissionStatus`:

```diff-typescript
 export interface EchoPlugin {
   echo(options: { value: string }): Promise<{ value: string }>;
+  checkPermissions(): Promise<PermissionStatus>;
+  requestPermissions(): Promise<PermissionStatus>;
 }
```

However, the implementation in line 89 uses `PermissionState`:

```diff-typescript
+import { PermissionState } from './definitions';

 export class EchoPluginWeb extends WebPlugin implements EchoPlugin {
   async echo(options: { value: string }) {
     ...
   }

+  async checkPermissions(): Promise<PermissionState> {
+    // TODO
+  }

+  async requestPermissions(): Promise<PermissionState> {
+    // TODO
+  }
 }
```

Or am I missing something?

**Comment by thomasvidas** [comment]
Oh yeah you are correct. Yikes even I got confused looking at it! This should probably be changed to `MyPermissionState` or something to be more explicit

**Review by jcesarmobile — APPROVED** [review]
good catch, thanks!

**Pull request merged**
