### PR TITLE
edit requirements; add subdirs ignored on Android

### PR DESCRIPTION
**Pull request by brodybits**
After spending 1-2 hours investigating, reproducing, and raising <https://github.com/ionic-team/capacitor/issues/3466>, duplicate of the "feature" discussed in <https://github.com/ionic-team/capacitor/issues/1750>, I hope this can help some others in the future.

### CODE REVIEW

**Comment by dwieeb** [comment]
Thanks for the PR!

I think this would be better in the Android docs, perhaps in the Troubleshooting section? There are plenty of other platform-specific quirks and listing them in "Getting Starting" might be premature and too much information at once.

**Comment by brodybits** [comment]
Thanks for the fast response. I would definitely agree that documenting this kind of quirk or pitfall would be a bit too much for a "Getting Started" section.

That said, I did not even think of looking for a troubleshooting section somewhere, and I would also not consider this information to be very easy for a newcomer to find through a Google search.

Given that I am coming from years of experience with some similar technology, I would consider this pitfall to be a pretty frustrating experience lurking for people coming from an average kind of web development background.

I am very hopeful that we can find a way to improve the experience for this kind of people, and I thought of a couple possible ideas:

- Move the "adding Capacitor to an existing app" information into another page and add a reference to the "Getting Started" page, in a similar fashion to "Using Capacitor with Ionic"
- Update the tooling, or add a new command-line tool, so that a user could add Capacitor to an existing project with 1-2 commands. The tool would check that `package.json` exists, take care of adding packages such as `@capacitor/core` if needed, list caveats such as the need for `head` element and the pitfall on Android, and tell the user what commands to run next.

**Comment by dwieeb** [comment]
I agree about moving "adding Capacitor to an existing app" to its own page.

As for the underscore issue, I am discussing the option of setting `ignoreAssetsPattern` in new Capacitor apps. The default pattern may make sense for Android apps, but certainly not when they contain web assets. So, it may make sense to provide a sensible default. I'll update this issue soon with what we came up with.

**Comment by brodybits** [comment]
Thanks. I think the most important issue is with newbies getting tripped up by the underscore issue, as we have seen on GitHub. It would probably be ideal if we can avoid this underscore issue by default.

The configuration option definitely sounds nice. I guess Gradle would just read the option when building?

**Comment by dwieeb** [comment]
@brodybits The changes in [this PR](https://github.com/ionic-team/capacitor/pull/3496) should fix this for new Capacitor 3 apps. We are overriding the `ignoreAssetsPattern` option for aapt.

**Pull request closed without merging**
